"""update health_unit_name field for not null

Revision ID: 1c95df070b4b
Revises: e043a19e17d1
Create Date: 2022-04-22 13:07:36.636216

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c95df070b4b"
down_revision = "e043a19e17d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vaccine_cards", "health_unit_name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vaccine_cards", "health_unit_name", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
