"""populate database

Revision ID: e043a19e17d1
Revises: 057adbd86aeb
Create Date: 2022-04-09 15:46:22.421072

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e043a19e17d1"
down_revision = "057adbd86aeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "vaccine_cards", ["cpf"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vaccine_cards", type_="unique")
    # ### end Alembic commands ###
